//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_Sibers.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_ProjectsDBEntities : DbContext
    {
        public Test_ProjectsDBEntities()
            : base("name=Test_ProjectsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectWorker> ProjectWorker { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
