//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_Sibers.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.ProjectWorker = new HashSet<ProjectWorker>();
        }
        [UIHint("GetWorker")]
        public int ID { get; set; }
        [DisplayName("»м€")]
        [Required(ErrorMessage = "¬ведите им€")]
        public string FirstName { get; set; }
        [DisplayName("‘амили€")]
        [Required(ErrorMessage = "¬ведите фамилию")]
        public string SecondName { get; set; }
        [DisplayName("ќтчество")]
        [Required(ErrorMessage = "¬ведите отчество")]
        public string ThirdName { get; set; }
        [DisplayName("E-mail")]
        [Required(ErrorMessage = "¬ведите e-mail")]
        [EmailAddress(ErrorMessage = "¬ведите e-mail корректно")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectWorker> ProjectWorker { get; set; }
        public string FullName        {
            get
            {
                return string.Format("{0} {1} {2}", SecondName, FirstName,ThirdName);
            }
        }
    }
}
